steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["run", "deploy","--image=gcr.io/$PROJECT_ID/cra-test/cra-image"]

images:
  - "gcr.io/$PROJECT_ID/cra-test/cra-image"
